mm_samychan_frontend:
    resource: "@MMSamyChanFrontendBundle/Resources/config/routing.yml"
    prefix:   /

mm_samychan_backend:
    resource: "@MMSamyChanBackendBundle/Resources/config/routing.yml"
    prefix:   /backend