# http://helpdesk.kdgforum.de/wiki/DVB_Service-Informationen
scm_config:
    series:
        D:
            files:
                map-CableD: CableD-320
                map-AirA: AirA-64
                map-AirD: AirD-320
                map-SateD: SateD-172
                map-AstraHDPlusD: AstraHDPlusD-212
        E:
            files:
                map-CableD: CableD-320
                map-AirA: AirA-64
                map-AirD: AirD-320
                map-SateD: SateD-168
                map-AstraHDPlusD: AstraHDPlusD-212
                map-FreesatD: FreesatD-320
        F:
            files:
                map-CableD: CableD-320
                map-AirA: AirA-64
                map-AirD: AirD-320
                map-SateD: SateD-168
                map-AstraHDPlusD: AstraHDPlusD-212
                map-FreesatD: FreesatD-320
        H:
            files:
                map-CableD: CableD-320
                map-AirA: AirA-64
                map-AirD: AirD-320
                map-SateD: SateD-168
                map-AstraHDPlusD: AstraHDPlusD-212
                map-FreesatD: FreesatD-320
        J:
            files:
                dvbc: dvbc-sqlite
                dvbs: dvbc-sqlite
                dvbt: dvbc-sqlite
                astra_192e: dvbc-sqlite
                freesat: dvbc-sqlite
    file_meta_data:
        map-CableD:
            label: Cable Digital
            icon: fa-signal
        map-AirA:
            label: Terrestrial Analog
            icon: fa-globe
        map-AirD:
            label: Terrestrial Digital
            icon: fa-globe
        map-SateD:
            label: Satelite Digital
            icon: fa-globe
        map-AstraHDPlusD:
            label: AstraHDPlus Digital
            icon: fa-globe
        map-FreesatD:
            label: Freesat
            icon: fa-globe
        dvbc:
            label: Cable Digital
            icon: fa-signal
        dvbt:
            label: Terrestrial Digital
            icon: fa-signal
        dvbs:
            label: Satelite Digital
            icon: fa-global
        astra_192e:
            label: Satelite Digital
            icon: fa-globe
        freesat:
            label: Freesat
            icon: fa-globe







