FreesatD-320:
    type: binary
    byte_length: 320
    fields:
        channelNo:
            label: No
            offset: 0
            length: 2
            type: MM\SamyChan\BackendBundle\Scm\DataType\SignedInteger16
            editable: true
            saveable: true
            rendering:
                render: editable
                className: number
        name:
            label: Name
            offset: 64
            length: 100
            type: MM\SamyChan\BackendBundle\Scm\DataType\String
            editable: true
            saveable: true
            rendering:
                render: editable
        fav1sort:
            label: F1
            offset: 292
            length: 4
            type: MM\SamyChan\BackendBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: checkbox
        fav2sort:
            label: F2
            offset: 296
            length: 4
            type: MM\SamyChan\BackendBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: checkbox
        fav3sort:
            label: F3
            offset: 300
            length: 4
            type: MM\SamyChan\BackendBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: checkbox
        fav4sort:
            label: F4
            offset: 304
            length: 4
            type: MM\SamyChan\BackendBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: checkbox
        fav5sort:
            label: F5
            offset: 308
            length: 4
            type: MM\SamyChan\BackendBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: checkbox