mm_samy_editor_homepage:
    path:     /
    defaults: { _controller: MMSamyChanBackendBundle:Default:index }

mm_samy_editor_scm_package_upload:
    path:     /upload/
    defaults: { _controller: MMSamyChanBackendBundle:ScmPackage:upload }

mm_samy_editor_content_imprint:
    path:     /imprint/
    defaults: { _controller: MMSamyChanBackendBundle:Content:imprint }

mm_samy_editor_content_exportscm:
    path:     /export-channel-list-samsung/
    defaults: { _controller: MMSamyChanBackendBundle:Content:exportscm }

mm_samy_editor_scm_package:
    path:     /{hash}.html
    defaults: { _controller: MMSamyChanBackendBundle:ScmPackage:index }

mm_samy_editor_scm_package_download:
    path:     /{hash}/download/
    defaults: { _controller: MMSamyChanBackendBundle:ScmPackage:download }

mm_samy_editor_scm_file:
    path:     /{hash}/file/{scmFileId}/
    defaults: { _controller: MMSamyChanBackendBundle:ScmFile:file }

mm_samy_editor_scm_favorites:
    path:     /{hash}/favorites/{favNo}/
    defaults: { _controller: MMSamyChanBackendBundle:ScmFavorite:index }

mm_samy_editor_scm_file_json:
    path:     /{hash}/file/{scmFileId}/json/
    defaults: { _controller: MMSamyChanBackendBundle:ScmFile:fileJson }

mm_samy_editor_scm_file_reorder:
    path:     /{hash}/file/{scmFileId}/reorder/
    defaults: { _controller: MMSamyChanBackendBundle:ScmFile:fileReorder }

mm_samy_editor_scm_channel:
    path:     /{hash}/channel/{scmChannelId}/
    defaults: { _controller: MMSamyChanBackendBundle:ScmChannel:channel }

mm_samy_editor_demo_load:
    path:     /demo/load/
    defaults: { _controller: MMSamyChanBackendBundle:Demo:load }