AirA-64:
    type: binary
    byte_length: 64
    fields:
        channelNo:
            label: No
            offset: 9
            length: 2
            type: MM\SamyEditorBundle\Scm\DataType\SignedInteger16
            editable: true
            saveable: true
            rendering:
                render: editable
                className: number
        name:
            label: Name
            offset: 20
            length: 10
            type: MM\SamyEditorBundle\Scm\DataType\String
            editable: true
            saveable: true
            rendering:
                render: editable
        fav1sort:
            label: F1
            offset: 36
            length: 4
            type: MM\SamyEditorBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: boolean
        fav2sort:
            label: F2
            offset: 40
            length: 4
            type: MM\SamyEditorBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: boolean
        fav3sort:
            label: F3
            offset: 44
            length: 4
            type: MM\SamyEditorBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: boolean
        fav4sort:
            label: F4
            offset: 48
            length: 4
            type: MM\SamyEditorBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: boolean
        fav5sort:
            label: F5
            offset: 52
            length: 4
            type: MM\SamyEditorBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: boolean