SateD-172:
    type: binary
    byte_length: 172
    fields:
        channelNo:
            label: No
            offset: 0
            length: 2
            type: MM\SamyEditorBundle\Scm\DataType\SignedInteger16
            editable: true
            saveable: true
            rendering:
                render: editable
                className: number
        name:
            label: Name
            offset: 36
            length: 100
            type: MM\SamyEditorBundle\Scm\DataType\String
            editable: true
            saveable: true
            rendering:
                render: editable
        vpid:
            label: VPID
            offset: 2
            length: 2
            type: MM\SamyEditorBundle\Scm\DataType\SignedInteger16
            rendering:
                className: number
        pcr:
            label: PCR
            offset: 4
            length: 2
            type: MM\SamyEditorBundle\Scm\DataType\SignedInteger16
            rendering:
                className: number
        sid:
            label: SID
            offset: 16
            length: 2
            type: MM\SamyEditorBundle\Scm\DataType\UnsignedInteger16
            rendering:
                className: number
        serviceType:
            label: Type
            offset: 14
            length: 1
            type: MM\SamyEditorBundle\Scm\DataType\ServiceType
            rendering:
                className: number
                render: serviceType
        encrypted:
            label: Crypt
            offset: 136
            length: 1
            type: MM\SamyEditorBundle\Scm\DataType\Boolean
            rendering:
                type: boolean
        fav1sort:
            label: F1
            offset: 140
            length: 4
            type: MM\SamyEditorBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: boolean
        fav2sort:
            label: F2
            offset: 144
            length: 4
            type: MM\SamyEditorBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: boolean
        fav3sort:
            label: F3
            offset: 148
            length: 4
            type: MM\SamyEditorBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: boolean
        fav4sort:
            label: F4
            offset: 152
            length: 4
            type: MM\SamyEditorBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: boolean
        fav5sort:
            label: F5
            offset: 156
            length: 4
            type: MM\SamyEditorBundle\Scm\DataType\SignedInteger32
            saveable: true
            rendering:
                type: boolean