mm_samy_editor_homepage:
    path:     /
    defaults: { _controller: MMSamyEditorBundle:Default:index }

mm_samy_editor_scm_package_upload:
    path:     /upload/
    defaults: { _controller: MMSamyEditorBundle:ScmPackage:upload }

mm_samy_editor_scm_package:
    path:     /{hash}/
    defaults: { _controller: MMSamyEditorBundle:ScmPackage:index }

mm_samy_editor_scm_package_download:
    path:     /{hash}/download/
    defaults: { _controller: MMSamyEditorBundle:ScmPackage:download }

mm_samy_editor_scm_file:
    path:     /{hash}/file/{scmFileId}/
    defaults: { _controller: MMSamyEditorBundle:ScmFile:file }

mm_samy_editor_scm_favorites:
    path:     /{hash}/favorites/{favNo}/
    defaults: { _controller: MMSamyEditorBundle:ScmFavorite:index }

mm_samy_editor_scm_file_json:
    path:     /{hash}/file/{scmFileId}/json/
    defaults: { _controller: MMSamyEditorBundle:ScmFile:fileJson }

mm_samy_editor_scm_file_reorder:
    path:     /{hash}/file/{scmFileId}/reorder/
    defaults: { _controller: MMSamyEditorBundle:ScmFile:fileReorder }

mm_samy_editor_scm_channel:
    path:     /{hash}/channel/{scmChannelId}/
    defaults: { _controller: MMSamyEditorBundle:ScmChannel:channel }
